### ISSUE TITLE
Ability to retrieve underlying logger

### ISSUE THREAD

**Issue by dan-j** [go-logr/logr#11]
I'm currently using https://github.com/cloudevents/sdk-go which allows you to set the zap logger for it use internally.

I'm using zapr in my application and would like to access the underlying logger so that I can configure cloudevents. The part of my application which is using the cloudevents SDK only has access to the logr instance.

I could configure the cloudevents SDK in the `main` package (where the logger is configured), however it seems a bit of a hack as only a portion of my application is using cloudevents.

Maybe adding a function to the `Logger` interface, something along the lines of:

```go
type Logger interface {
    ...
    Underlying() interface{}
}
```

I'm aware this would break the interfaces of each wrapper, so would require updating those packages. This could be mitigated temporarily with a new interface and once all wrapper libraries are updated, merge back into the single interface? Like:

```go
type LoggerWithUnderlying {
    logr.Logger
    Underlying() interface {}
}
```

What are your thoughts? Happy to contribute a PR

**Comment by thockin** [comment]
I don't hate it, and it seems pragmatic.  Given that this API is very pre-release, I am not worried about breaking changes, either.

@DirectXMan12 - thoughts?

**Comment by DirectXMan12** [comment]
I don't love it, but yeah, it seems pragmatic.  The other option is to specifically do this on a per backend basis -- i.e. have an interface

```go
type ToZapLogger interface {
  UnderlyingZap() zap.Logger
```

for Zapr.  Since you can't really do anything with underlying w/o knowing what it is anyway, I think that might make a teensy bit more sense.

**Comment by DirectXMan12** [comment]
Plus, it allows for logging implementations that *don't* have an underlying logger.

**Comment by thockin** [comment]
I like it.  Each logr impl has to define their own public way of getting
this, but yeah:

https://play.golang.org/p/ts2EY6PX0-J
