### ISSUE TITLE
Need for `Logger.UpdateValues()`

### ISSUE THREAD

**Issue by roy2220** [go-logr/logr#117]
We use a bunch of web middlewares, if a web middleware needs to attach contextual information into the logger, we can achieve it as below:

```
...
logger, _ := logr.FromContext(ctx)
newLogger := logger.WithValues("foo", foo, "bar", bar)
ctx = NewContext(ctx, newLogger)
...
```

Since there are so many middlewares attaching contextual information into the logger, it will end up making a long chain of Contexts (Refer to [the source](https://cs.opensource.google/go/go/+/refs/tags/go1.17.2:src/context/context.go;l=562)), and only the last Context that carries a logger would be used.

If there is a method for logger (e.g. UpdateValues) that appends new values into the existing logger without spawning a new logger, the long chain of Contexts could be avoided:

```
...
logger, _ := logr.FromContext(ctx)
logger.UpdateValues("foo", foo, "bar", bar)
...
```

**Comment by wojas** [comment]
The problem with an `UpdateValues` is that it could affect completely unrelated code if misused and not be safe if used from multiple goroutines without locking. The Logger object is also always passed by value, so this would not even be possible without a breaking change.

The best way to use logr is to explicitly pass it as an extra parameter. The `FromContext` thing is a kludge to enable passing the logr object to existing AP and can not easily be changed to take this extra parameter. Unfortunately, the HTTP handler is such an API.

You can always create a wrapper func to mitigate the verbosity, something like:

```go
func getLogger(ctx context.Context, kv ...interface{}) (newCtx context.Context, logger logr.Logger) {
	logger, _ := logr.FromContext(ctx)   // FIXME: handle error
	newLogger := logger.WithValues(kv...)
	newCtx := logr.NewContext(ctx, newLogger)
	return newCtx, newLogger
}

func example(ctx context.Context) {
	...
	ctx, logger := getLogger(ctx, "foo", foo, "bar", bar)
	...
}
```

Rebinding the ctx whenever you change or add something to it is nothing new.

**Comment by roy2220** [comment]
@wojas The long chain of Contexts involves the performance issue, since the time complexity of `context.Value()`  is O(N).

If we explicitly pass the logger as an extra parameter, it will quickly spread everywhere, become another `ctx Context` (Context is considered bad for its infectious nature).

I'm going to create a 'pointer version' of NewContext/FromContext for my own usage:
```
// Bind pointer of logger to ctx
logger := logr.New(...)
ctx = context.WithValue(ctx, MyContextKey{}, &logger) 

...

// Get pointer of logger from ctx
logger := context.Value(MyContextKey{}).(*logr.Logger)
*logger = *logger.WithValues(...) // Update logger in place
```

**Comment by pohly** [comment]
> (Context is considered bad for its infectious nature).

Rock and hard place... any approach for passing additional information into a function call chain has to be "infectious" because if you don't pass something in via a parameter, any function further down the chain lacks access to the additional information.

Thread-local storage would solve that, but as far as I know, Go doesn't support that.

IMHO passing `ctx context.Context` is the best (least evil?) solution because it can handle deadlines as well as additional values.

**Comment by pohly** [comment]
> I'm going to create a 'pointer version' of NewContext/FromContext for my own usage:
>
> ```
> logger := context.Value(MyContextKey{}).(*logr.Logger)
> *logger = *logger.WithValues(...) // Update logger in place
> ```

So a called function is going to permanently add values to the logger that its caller is still using? That sounds odd.

**Comment by pohly** [comment]
It's also not safe once you have goroutines: overwriting `*logger` which may be read somewhere is not atomic, so you end up with a read/write race.

**Comment by roy2220** [comment]
@pohly Yes, this way is not concurrency-safe indeed.
In my case, `*logger` will only be overwrote by middlewares in order, `*logger` will be 'stable' after that.

BTW, zerolog has a method similar to `UpdateValues`:

> func (l *Logger) UpdateContext(update func(c Context) Context)
   UpdateContext updates the internal logger's context.
   Use this method with caution. If unsure, prefer the With method.

Refer to https://pkg.go.dev/github.com/rs/zerolog#Logger.UpdateContext

**Comment by roy2220** [comment]
@pohly Immutability is good for concurrency, but it usually comes with a performance cost. I think it's hard to reach a solution/conclusion here,  thanks for your time!
