### ISSUE TITLE
change log entry details depending on log level

### ISSUE THREAD

**Issue by pohly** [go-logr/logr#126]
This might be another one of my ideas that aren't useful enough in practice, but let me share it anyway...

In a few places in Kubernetes, `if Enabled()` is used to choose between two different log calls where the difference is the amount of information that gets logged. In other words, at higher log levels one does not only get more log entries, but also more detailed ones.

This can be done at the call site with the existing API, but it becomes less readable:
```
if logV := logger.V(5); logV.Enabled() {
    logV.Info("hello", "v1", 1, "v3", 3, "v5", 5)
else if logV := logger.V(3); logV.Enabled() {
    logV.Info("hello", "v1", 1, "v3", 3)
} else {
    log.V(1).Info("hello", "v1", 1)
}
```
One option would be to create a `[]interface{}` slice with the parameters. The klog logchecker will complain about that, though, because it cannot do a static analysis that the key/value pairs are well-formed:
```
kv := []interface{}{"v1", 1}
if logger.V(3).Enabled() {
    kv := append(kv, "v3", 3)
    if logger.V(5).Enabled() {
        kv := append(kv, "v5", 5)
    }
}
log.V(1).Info("hello", kv...)
```

This could remain a single call if we had a way to express verbosity of each key/value pair, for example like this:
```
log.V(1).Info("hello", "v1", 1, logr.KeyV(3, "v3"), 3, logr.KeyV(5, "v5"), 5)
```

```
func KeyV(int level, key string) { return keyV{level: level, key: key} }

type keyV struct {
    level int
    key string
}

func (k keyV) String { return k.key }
func (k keyV) Level int { return k.level }

type LeveledStringer interface {
    fmt.Stringer
    Level() int
}
```

Loggers which support this could check for this interface and skip key/value pairs which are above the threshold. Those that don't still can construct a string key, without having to be modified.

**Comment by thockin** [comment]
I have to say, I am not super excited about this.  I get the point, I think, but I'm not sure it's very clear or valuable enough.  Convince me?

**Comment by wojas** [comment]
Typically when you want to do this, the information you want to add to the log is expensive to obtain. In that case the `KeyV` would not do much to to help. 

I would usually just generate extra log messages for the details, but I can see how extra attributes could be useful.

If you really must, how about just doing the following?

```go
var extra []interface{}
if logger.V(3).Enabled() {
    extra = append(extra, "v3", 3)
    if logger.V(5).Enabled() {
       extra = append(extra, "v5", 5)
    }
}
log.V(1).Info("hello", "v1", 1, extra...)
```

This way:

- The extra attributes can be reused for multiple log calls
- They can be generated by a reusable function

Or perhaps even better:

```go
if logger.V(3).Enabled() {
    log = log.WithFields("v3", 3) 
    if logger.V(5).Enabled() {
        log = log.WithFields("v5", 5) 
    }
}
```

**Comment by thockin** [comment]
I rather like the last approach

**Comment by pohly** [comment]
> I have to say, I am not super excited about this. I get the point, I think, but I'm not sure it's very clear or valuable enough. Convince me?

I'm not going to try because I have concerns myself :grin: I just wanted to bring it up for discussion.

I also like the last approach. We cannot currently use it in Kubernetes because we are still stuck with structured logging via klog which doesn't have WithFields, but perhaps [that'll change](https://github.com/kubernetes/enhancements/pull/3078).

/close
