### ISSUE TITLE
Would it be possible to rename pkg testing?

### ISSUE THREAD

**Issue by rollulus** [go-logr/logr#138]
The use case of `"github.com/go-logr/logr/testing"` is for testing, and in tests an import of stdlib's `"testing"` is guaranteed. Hence, any use of `"github.com/go-logr/logr/testing"` requires to alias the import by definition. Would it be possible to give it a smarter name instead? Or, because a rename will break backwards compatibility, would it make sense to create a `testr` pkg in the same spirt as `zapr`, `stdr`, etc.?

**Comment by thockin** [comment]
I could see creating a `testr` subdir, moving `testing.NewTestLogger` -> `testr.NewTestr`, `testing.Options` -> `testr.Options`, etc, and then aliasing them from their old names in `testing`.  

We could soft-deprecate `testing`, but leave it alive indefinitely.

PRs welcome - it seems straightforward and reasonable, but the devil's always in the details.
