### ISSUE TITLE
"go get github.com/go-logr/logr/funcr" got error

### ISSUE THREAD

**Issue by wangqiao92** [go-logr/logr#139]
# github.com/go-logr/logr/funcr
../../go/src/github.com/go-logr/logr/funcr/funcr.go:398:16: undefined: strconv.FormatComplex
../../go/src/github.com/go-logr/logr/funcr/funcr.go:400:16: undefined: strconv.FormatComplex
../../go/src/github.com/go-logr/logr/funcr/funcr.go:443:16: undefined: strconv.FormatComplex
../../go/src/github.com/go-logr/logr/funcr/funcr.go:445:16: undefined: strconv.FormatComplex

**Comment by pohly** [comment]
Your version of Go is too old. Can you update it?

**Comment by thockin** [comment]
Specifically, is there a reason you NEED such an old version of Go?

**Comment by h1z3y3** [comment]
Same issue. We use `go.opentelemetry.io/otel`

```shell
> go mod why github.com/go-logr/logr
# github.com/go-logr/logr
github.com/beego/beego/v2/client/httplib/filter/opentelemetry
go.opentelemetry.io/otel
github.com/go-logr/logr
```

Github CI Error:

https://github.com/beego/beego/runs/5740325469?check_suite_focus=true

**Comment by thockin** [comment]
Same response - is it impossible to use a more modern version of Go (i.e.
Released in the last 2 years)?  There are lots of bugs and improvements...
