### ISSUE TITLE
Structured logging idea

### ISSUE THREAD

**Issue by mtaufen** [go-logr/logr#14]
@thockin and I had an offline chat about structured logging (some related to https://github.com/kubernetes/enhancements/pull/1367) and one idea that came up was that some sort of tuple type might speed up logging performance. One concern was that tuples might be annoying to express in go, if you have to include a type annotation with each instantiation. But it turns out you don't need this, as long as the slice is annotated, so you can do something like this:

```
package main

import (
	"fmt"
)

type S struct {
	k string
	v interface{}
}

func Log(m string, args ...S) {
	fmt.Println(m, args)
}

func main() {
	type N struct {
		n string
	}
	a := N{"foo"}
	b := N{"bar"}
	Log("test", []S{{"foo", a}, {"bar", b}}...)
}
```

You can also invoke `Log` like `Log("", S{"foo", a}, S{"bar", b})`, but with an import prefix on the annotation that can get verbose. Either way, it would be up to the user how to invoke it.

Tim asked me to file an issue with these notes, so here it is :-).

/assign @thockin

**Comment by thockin** [comment]
```
mylogger.Info("something happened", []logr.V{{"key", value}, {"other", thing}})
// vs
mylogger.Info("something happened", "key", value, "other", thing)
```

**Comment by mtaufen** [comment]
Yes. Probably needs a benchmark to justify.

**Comment by thockin** [comment]
Not happening for v1.
