### ISSUE TITLE
View logs with verbosity level set

### ISSUE THREAD

**Issue by ssmails** [go-logr/logr#141]
I have set the verbosity level as follows, as I essentially would like these to be like Debug level logs-
l.Log.V(10).Info("req reconciled", "req", req.NamespacedName)

How do I ensure these logs get printed, when  I do want to view the logs at this verbosity level ?
Currently I only see the logs printed at l.Log.Info , which is default verbosity level as 0.

**Comment by pohly** [comment]
> How do I ensure these logs get printed, when I do want to view the logs at this verbosity level ?

That is determined by the Logger implementation that you are using. For example, klog has a -v parameter that sets the threshold.

**Comment by ssmails** [comment]
we use the below to set the Logger

ctrl "sigs.k8s.io/controller-runtime"

	opts := zap.Options{
		Development: true,
	}
ctrl.SetLogger(zap.New(zap.UseFlagOptions(&opts)))

Then use that Logger.
	reconciler := &controllers.GatewayConfigReconcilerLog{
		Log: ctrl.Log.WithName("controllers").WithName("GatewayConfig"),
	}

GatewayConfigReconcilerLog is using below, 
type GatewayConfigReconcilerLog struct {
	Log  logr.Logger
}

Now, when I have the Development mode set to true as above in the Logger options, I would expect to see level 10 logs printed, but I dont. As per docs of this package debug is level 10.
l.Log.V(10).Info("req reconciled", "req", req.NamespacedName)

**Comment by pohly** [comment]
What is this `zap` package here?

You have to configure zap to enable log levels that are even lower (numerically) than Debug. See this code:
- https://github.com/go-logr/zapr/blob/df10f4788c061a53564cebafc055fd9ad3f3255e/zapr.go#L194-L202
- https://github.com/kubernetes/kubernetes/blob/f02682c628c530219966a00ae002d799f0d813dc/staging/src/k8s.io/component-base/logs/json/json.go#L38-L77

**Comment by thockin** [comment]
https://github.com/go-logr/zapr/blob/master/example/main.go#L42-L47 show a trivial example of setting the zapr level, too.
