### ISSUE TITLE
Feature request; GetV() function

### ISSUE THREAD

**Issue by uablrek** [go-logr/logr#149]
The [glog.V()](https://pkg.go.dev/github.com/golang/glog#V) function allows;
```go
if glog.V(2) { glog.Info("log this") }
```
This is the reason;

> The second form is shorter but the first is cheaper if logging is off because it does not evaluate its arguments. 

To not evaluate the arguments can be _very important_ for instance if a function is called that searches 100,000 objects for some crucial trace info. You _do not_ want to to that if not on trace level, like V(2). Even though the glog implementation is pretty cool I realize it may not be feasable for `logr`, but a possibility to read the V-level should be provided.

**Comment by pohly** [comment]
The same works with logr:
```
   if loggerV := logger.V(5); loggerV.Enabled() {
       // Do something expensive.
      loggerV.Info("here's an expensive log message", ...)
   }
```

Note that the log call reuses the result of `logger.V(5)`. That ensures that logger implementations which record the log level pick the right one.

**Comment by uablrek** [comment]
Thanks! But this is not really intuitive (at least not for me) so IMHO it should be documented with an example.

**Comment by pohly** [comment]
Feel free to add it somewhere, PR welcome.
