### ISSUE TITLE
New release to ship #143

### ISSUE THREAD

**Issue by Zerpet** [go-logr/logr#156]
Hey there 👋 PR #143 was merged a few months ago, however, it is not in any release (last release 1.2.3 does not include this feature). Any chance you could produce a new release with this feature?

I'd like to avoid pinning my dependency to `@master` or to a specific commit, if possible. Thank you!

**Comment by thockin** [comment]
I'd like to get a few more pending PRs in then, yes.

**Comment by thockin** [comment]
@pohly let's decide on #167 and then tag a new release?

**Comment by pohly** [comment]
I agree, that seems to be the last blocker.

**Comment by thockin** [comment]
https://github.com/go-logr/logr/releases/tag/v1.2.4
