### ISSUE TITLE
Create `charmbracelet/log` implementation

### ISSUE THREAD

**Issue by Dentrax** [go-logr/logr#172]
https://github.com/charmbracelet/log is popular, minimal and colorful Go logging library. It'd be nice to add this to supported list.

**Comment by pohly** [comment]
Are you offering to implement a LogSink implementation for that or are you looking for someone else to do it?

Do you have evidence that it is popular? zap gets imported [47814 times](https://pkg.go.dev/go.uber.org/zap), charmbracelet/log [47 times](https://pkg.go.dev/github.com/charmbracelet/log) according to gopkg.

**Comment by Dentrax** [comment]
I'm just dropping the idea here for discuss more about. If anyone want to implement LogSink, please go ahead.

> Do you have evidence that it is popular

Actually I was looked at star count rather than import count. Definitely import count much more better metric for sure.

**Comment by thockin** [comment]
If/when there's a LogSink implementation for it we can consider it.  I know neither @pohly nor I have time to do the implementation ourselves right now :)

**Comment by thockin** [comment]
Sorry, I see the PR now.
