### ISSUE TITLE
why `V` function make level additive?

### ISSUE THREAD

**Issue by fovgrubby128** [go-logr/logr#174]
When I read the code, I have a question. Why `V` function make level additive, instead of setting the level to the value I put?

For example, I had a `logger` from `log.FromContext(ctx)`. 

The first time, I wanted to log the msg at level 2, thus I did `logger.V(2).Info(msg..)`

Later, I wanted to log the msg at level 3, however, if I did `logger.V(3).Info(msg...)`, it logged it at level (2+3 = 5), which was not expected.

And I feel make it additive, would make it difficult to get the log level from this logger when I want to use it, since I need to calculate the total value where I called this function.

**Comment by fovgrubby128** [comment]
sorry...my bad..I mis-read the code..

**Comment by thockin** [comment]
It is additive ONLY IF you save the intermediate Logger.
