### ISSUE TITLE
How could I transfer the caller information into Json format?

### ISSUE THREAD

**Issue by fovgrubby128** [go-logr/logr#175]
Hi team, I'm not sure whether this is the most proper place to post this question, but please allow me post it here first.

The context: I put `klogr.New()` into log context in the controller manager. Thus, in each reconciler(I use `controller-runtime` package), it would be fetched via `logger := log.FromContext(ctx)`, and its type is `logr.Logger`. However, I noticed in the output logging, besides `msg`, it would also contain the caller information, for example,
```
2023-04-01T23:23:41.782907481Z stderr F I0401 23:23:41.782665       1 xxxx_reconciler.go:100] controller/xxx "msg"="random msg", ....
```

Thus, in the Loki from Grafana, it would output as a plain text string, but not in a json format though I set json format in `klogr`. Could I know where those caller information comes from? Also how could we transfer them into json format?

Thanks!

**Comment by pohly** [comment]
How do you set "json format in `klogr`"?


https://github.com/kubernetes/klog/tree/main/klogr doesn;t really do proper JSON formatting. For that you need some other logr implementation.

**Comment by fovgrubby128** [comment]
> How do you set "json format in `klogr`"?
> 
> https://github.com/kubernetes/klog/tree/main/klogr doesn't really do proper JSON formatting. For that you need some other logr implementation.

oh..I thought https://pkg.go.dev/k8s.io/klog/v2/klogr#New would make it output into json format. And I checked the output, it would have `msg`, following `key1`=`value1`, `key2`=`value2`... That's why I think the reason that it did not output as json format in Loki is due to the caller information...

Also, `For that you need some other logr implementation.` Could I know how to do that? thanks!

**Comment by pohly** [comment]
For example, in Kubernetes we use zapr.

https://github.com/kubernetes/component-base/blob/master/logs/example/example.go

**Comment by fovgrubby128** [comment]
> For example, in Kubernetes we use zapr.
> 
> https://github.com/kubernetes/component-base/blob/master/logs/example/example.go

hmmm...I could not see `zapr` from the link you provided...

**Comment by pohly** [comment]
It's used in `component-base/logs/json`.
