### ISSUE TITLE
PR #166 introduced a breaking change in a patch release

### ISSUE THREAD

**Issue by makkes** [go-logr/logr#180]
We (the [Flux](https://github.com/fluxcd/flux2/) team) ran into a bug related to [this PR](#166). From our perspective the PR is breaking the assumption that `logr.Logger{} != logr.Discard()` and it actually led to a [bad bug](https://github.com/fluxcd/flux2/issues/3808) experienced by some of our users.

Since the change was introduced as part of a logr patch release (1.2.4) I wanted to let you know (and discuss) that this might be pretty unexpected given it's "just" a patch release and not a minor or major release and that the logr project states to be strict about [following semver](https://github.com/go-logr/logr/blob/master/CONTRIBUTING.md#compatibility).

Don't get me wrong, please. I think the change introduced in #166 is very good, it's just the unfortunate inclusion of it in a patch release that might lead to unforseen bugs in dependent code.

I'm happy to hear your people's opinion on this.

**Comment by makkes** [comment]
@thockin as discussed on Slack.

**Comment by pohly** [comment]
> logr.Logger{} != logr.Discard()

I don't think we ever promised that `logr.Discard()` is or is not equal to the zero value. The API only guaranteed that the `Logger` value can be compared and that `logr.Discard` always returns an equal value.

There is a comment that pointer to a logger should be used when detecting "no logger" is important: https://github.com/go-logr/logr/blob/5d5771278ebb6b08180d7cfd806af158964ebfc1/logr.go#L130-L133

Ignore the comment in that section about the null logger, that is out-dated. But it doesn't change the recommendation.

**Comment by thockin** [comment]
Oops!  We should fix that comment!

**Comment by pohly** [comment]
-> https://github.com/go-logr/logr/pull/182

**Comment by thockin** [comment]
@makkes - Given that we don't want to revert this - the options are either

a) you use `*Logger` to indicate optional Logger
b) you don't make it optional, and user says what they mean
c) we add API surface to indicate a difference between `Logger{}` and `Discard()`, which I think we don't want to do.

Are we OK to close this?

**Comment by makkes** [comment]
We already fixed our code and removed the conditional, basically opting for case b) you gave above.

Thanks for the clarification on expectations here, everyone!
