### ISSUE TITLE
Why use WithName()

### ISSUE THREAD

**Issue by ukiahsmith** [go-logr/logr#183]
What is the use case for `l.WithName("myName")` versus using `l.WithValues("name", "myName")`?

I was looking over the new `slog` documentation and did not see something similar. The closest they have is `WithGroup()` but it's not very close at all.

**Comment by thockin** [comment]
WithName can be accumulated each time it is called.  It doesn't SET the
logger name, it appends to it. It's implementation defined, but the results
can be more like a file path than a single name.

We have, so far, not convinced slog of the need for this function.

**Comment by ukiahsmith** [comment]
You are saying the benefit of WithName over WithValues is that it appends, where WithValues would replace.

It sounds like I would only use WithName if my log aggregation server supported the name-colon format.

**Comment by thockin** [comment]
WithName manipulates a "special" value. Implementations may emit it as a
regular value or do something else with it. It's not just another key.

**Comment by ukiahsmith** [comment]
I don't understand what you are saying. I appreciate your help. I think my question is, basically, when and why would I use WithName. The readme says to use it when passing different loggers to different libraries. My limited understanding of structured logging is that it is _always_ key value pairs. When you said "implementations" did you mean log sinks, or log server aggregators?

**Comment by thockin** [comment]
Sorry, I am on mobile :)

LogSink implementations can do anything thy like with the structured
key-value pairs. Nothing REQUIRES that they _only_ emit key-value output.
For example, it would be valid to emit a prefix like:

"""
I[04/29/2023 16:02.12345 foo.go:93] the message, key1=val1, key2=val2
"""

The WithValues() key-value pairs and the .Info() pairs are still keys and
values, but maybe the caller and timestamp are not. That's allowed.

So, about WithName() - an implementation could choose to emit it in that
prefix, or could emit it as a special key, or could ignore it completely.
It's not just another regular key.

The suggestion is to track it as a list of elements, like a path, which can
indicate which instance of Logger is emitting.

For example, I might have my root Logger initialized in main().  I spawn a
cache-manager goroutine and pass it rootlog.WithName(" cache").  When it
emits log lines I might get metadata that says logger="/cache".

That cache-subsystem might spawn a garbage-collector goroutine and pass it
cachelog.WithName("gc").  When it emits log lines I might get metadata that
says "logger=/cache/gc".

Does that make sense?

**Comment by ukiahsmith** [comment]
Yes, this makes more sense to me. Thank you for taking the time to type it all up.

> Nothing REQUIRES that they _only_ emit key-value output.

Okay, I understand this.

So, maybe, I create a LogSink that emits a prefix of an older log format for some old system that I still have to use, but also the key value pairs to be used in a new system. 

> So, about WithName() - an implementation could choose to emit it in that
prefix, or could emit it as a special key, or could ignore it completely.

This makes sense too.

I've been using logr/stdr which emits the name as a prefix, but a different LogSink could emit it as a key value pair, or anything it wanted to. If I were using a log aggregation server the I would use the LogSink (or build my own) that knows how to format the WithName() value so that whichever log server I am using would understand it.

**Comment by thockin** [comment]
Right. github.com/go-logr/logr/funcr, for example, emits strict JSON, and
the logger is just another value.
