### ISSUE TITLE
Create tag for v0.2.1

### ISSUE THREAD

**Issue by mattysweeps** [go-logr/logr#22]
Since https://github.com/go-logr/logr/issues/19 has been resolved, can a v0.2.1 release be cut?

**Comment by justenwalker** [comment]
[controller-runtime is doing this](https://github.com/kubernetes-sigs/controller-runtime/pull/1068/files#diff-37aff102a57d3d7b797f152915a6dc16R8) as a work-around

**Comment by thockin** [comment]
https://github.com/go-logr/logr/releases/tag/v0.2.1
