### ISSUE TITLE
Cut a new release (v1.4.0?)

### ISSUE THREAD

**Issue by thockin** [go-logr/logr#252]
When shall we tag a new release?

**Comment by pohly** [comment]
I think we are ready. https://github.com/go-logr/logr/pull/251 can be done later.

**Comment by pohly** [comment]
Perhaps double-check which of the open issues related to slog can be closed? I think several of the ideas around extending the sink interface are not needed now that we have `SlogSink`.

**Comment by thockin** [comment]
I'd like to keep the "Consider..." issues open for further thinking.

**Comment by thockin** [comment]
I'll draft a release - is v1.4.0 ok?

**Comment by thockin** [comment]
https://github.com/go-logr/logr/releases/edit/untagged-34b91841a84bc989f219

If you are happy, go ahead and push the button.

**Comment by thockin** [comment]
@veqryn

**Comment by pohly** [comment]
Published.
