### ISSUE TITLE
Add NullLogger

### ISSUE THREAD

**Issue by wojas** [go-logr/logr#26]
Following discussion in #25, it is probably a good idea to add a `null.Logger` to logr that ignores all messages.

This can be used as a default logger by components that optionally allow you to pass in a logger. If none is passed in, it can simply use the null logger for all its logging.

The implementation would live under a "null" subpackage and could look like this (needs doc comments):

```go
package null

import "github.com/go-logr/logr"

type Logger struct{}

func (n Logger) Enabled() bool {
	return false
}

func (n Logger) Info(msg string, keysAndValues ...interface{}) {
}

func (n Logger) Error(err error, msg string, keysAndValues ...interface{}) {
}

func (n Logger) V(level int) logr.Logger {
	return n
}

func (n Logger) WithValues(keysAndValues ...interface{}) logr.Logger {
	return n
}

func (n Logger) WithName(name string) logr.Logger {
	return n
}
```

Usage:

```
import "github.com/go-logr/logr/null"

func foo() {
	l := null.Logger{}
}
```

**Comment by thockin** [comment]
Do you want to send a PR for this or do you want me to just copy it and attribute you?  I am tempted to just leave it in the logr package.

**Comment by thockin** [comment]
Also - expose type or `func NewNull() Logger { return nullLogger{} }` ?

**Comment by wojas** [comment]
> Do you want to send a PR for this or do you want me to just copy it and attribute you? I am tempted to just leave it in the logr package.

After some thought I also came to the conclusion that it's better to put it at the logr package level, because the null logger needs to import the Logger interface, and then the main package would no longer be able to import the null logger due to a circular import.

I will add a PR for this and then we can further discuss the details there.
