### ISSUE TITLE
Metrics for logged messages

### ISSUE THREAD

**Issue by grzesuav** [go-logr/logr#265]
hi

is there an easy way to get metrics for specific logger, like how many error/info etc was recorded ?

**Comment by thockin** [comment]
This is not something we have today, but I am not against it, per se.

Do you thin it would be per-logger?  Or global?

What format would those come out as?

It's a little complicated to impose on impl.  Consider:

```
logger.V(1).Info("msg")
```

`logger` is a `logr.Logger`.  The call to `logger.V(1)` produces a different `logr.Logger` instance, so the metric accumulation would have to be ain internally-managed pointer, which means mutexes or careful use of atomic ops.  Not super difficult, but could be performance-impacting.

Are there examples of other log libraries that do this in a way that answers the questions you want to anwer?

**Comment by thockin** [comment]
That sounds like a global counter, which is easier to implement but is probably best served by an implementation-specific interface (e.g. logr is not going to take a dependency on Prometheus, but something like like zap or logrus might).

Is there any reason why logr (which is a thin shim on top of implementation hooks) should be involved instead?

**Comment by grzesuav** [comment]
I was thinking that implementing in logr make it independent from underlying logger. I will check if this is something which logger implementation could handle

**Comment by thockin** [comment]
To do it in logr itself would mean doing work (atomic ops) that was very possibly already done by the implementation, and still app-specific glue would be needed to "publish" the metrics (the best we could give would be integers).  Also, we don't know all the details outside of the `LogSink` - it might further collapse repeated lines or do arbitrary formatting, meaning the best we could do would be "this many calls to Info were made" but not "this many bytes were written".

`logr.Logger` really wants to be as thin and lightweight as possible.  We don't have an options struct or any config parameters on purpose.

This was a fun idea, but I don't think we want to do this in logr itself.
