### ISSUE TITLE
I am facing log/slog is no in std (/usr/local/go/src/log/slog)

### ISSUE THREAD

**Issue by Marinero0214222** [go-logr/logr#287]
Hi All,

I am using the following command to build shared library:
go build -buildvcs=false -buildmode=c-shared -gccgoflags="-s -w" -compiler=gccgo -o xxxx.so

but, finally, returns the final error message:
/home/sqc/go/pkg/mod/github.com/go-logr/logr@v1.4.1/context_slog.go:25:2: package log/slog is not in std (/usr/local/go/src/log/slog)

go version: go1.21.9 linux/amd64.

Please help to check if it is bug or not

Thanks,
Marinero

**Comment by pohly** [comment]
Double-check your Go installation. 1.21 should have log/slog: https://pkg.go.dev/log/slog@go1.21.0

**Comment by Marinero0214222** [comment]
Hi @pohly 

Yes. I checked. log/slog is present. but, still report this issue. are there other impacts?

Thanks,
Marinero

**Comment by pohly** [comment]
Perhaps `-compiler=gccgo`? Can you try without any flags?

**Comment by Marinero0214222** [comment]
Hi @pohly 

I found the size of binary built by gc is around 15MB. So, I want to try use gccgo to build and compare the size difference.But, facing this issue.

Can you give some proposals?

Thanks,
Marinero
