### ISSUE TITLE
Release 0.1.0

### ISSUE THREAD

**Issue by DirectXMan12** [go-logr/logr#3]
It'd be nice to have a pre-1.0 release so that it's a bit easier to specify versions in tools/libraries that consume it (e.g. controller-runtime).  Otherwise, they have to relying on pinning to specific git hashes, and that gets messy when pulling in multiple libraries that have dependencies on logr (e.g. library X depends on logr directly, plus zapr, which also depends on logr).

**Comment by DirectXMan12** [comment]
(it's not practically an issue quite yet, except that newer versions of dep complain a bit about certain combinations of master and SHA requirements, but it's generally a good idea to have some versioning down *before* you need to break things)

**Comment by thockin** [comment]
Sure, I'll tag it 0.1.0
