### ISSUE TITLE
Generic way to add options without breaking changes

### ISSUE THREAD

**Issue by wojas** [go-logr/logr#32]
This was originally a comment on PR #31 that implements the idea proposed in #30.

There will always be a demand for more options to the Logger interface, but we have to balance the added value of these new options with the impact on the ecosystem of breaking changes. Constant breaking changes to the interface make this project less attractive. Ideally we will be able to define a v1.0 that will remain stable for years to come, without too many breaking changes getting there.

I would like to find a generic way to add arbitrary options and then just break compatibility once to add this new interface.

For example, we could add this method to the interface:

```go
WithOption(option Option) Logger
```

with `Option` being some interface. This could be nothing more than an interface with some marker method that never actually gets called:

```go
type Option interface {
    LogrOption()
}
```

Then we could define a new `CallDepth` option, which you would use as follows:

```go
log = log.WithOption(logr.CallDepth(2))
```

Implementations would be required to ignore unknown options. Applications would be able to define their own custom options that get passed around.

We would always be able to add new 'official' options to the logr package without breaking the interface. 

If we also add something similar to convert the logger into something else, we may never have to break the Logger interface again:

```go
Convert(Conversion) interface{}
```

Usage example that would solve #11:

```go
underlying := log.Convert(logr.Underlying).(*logrus.Logger)
```

**Comment by pohly** [comment]
I like this approach.

**Comment by thockin** [comment]
I feel like I am missing something.  How does an implementation know which option was called?  Type assertion?  I guess that works.  We don't really even need an interface type - just pass anything you like and let the impl interpret.

But the same question from #30:

Do callers who SPECIFICALLY invoke this logic really want the implementation to ignore their request or would they rather compile fail and then think "oh right, I need to update logrus"?

And is that true for all future options?

Part of me feels this is scaffolding we'll never really need.  I do hope that once we hit 1.0 we'll be done.  How often do new features really land in logging libs that need to be evaluated on a per-abstract-Logger level?
