### ISSUE TITLE
All examples are based on main() only

### ISSUE THREAD

**Issue by isavcic** [go-logr/logr#39]
Hello, the README says:

> Ideally only `main()` knows what logging implementation is being used.

yet the examples, even of the various implementations, contain just the `main()` function.

Can you please provide a basic example how to use this across multiple packages in a single application, for beginners like me, explaining how to make the app/packages logging implementation-agnostic?

Thanks!

**Comment by thockin** [comment]
Updated!

**Comment by isavcic** [comment]
Sorry @thockin, what got updated?
