### ISSUE TITLE
Enforce WithValues to use key/value type

### ISSUE THREAD

**Issue by odacremolbap** [go-logr/logr#4]
`keysAndValues` are used at Error, Info and WithValues functions
```
WithValues(keysAndValues ...interface{}) Logger
```

Implementators will need to check for tuples, and deal with scenarios where odd number of parameters are passed. That sounds tricky at compile time.

A key value type like
```
type KV map[string]interface{}
```
would solve this problem, with the downside of enforcing key to be an string, which I guess is something we can take for granted.

**Comment by thockin** [comment]
That has the downside of making call-sites more verbose.  We could make a
logr.Values type so call sites would look something like:

```
logger.Info("the frobber is running", logr.Values{"name": name, "timeout",
timeout})
```

...but I am not sure it is worth the effort.  I am on mobile, but I can
chew on it a bit.
