### ISSUE TITLE
log file

### ISSUE THREAD

**Issue by GeorgeGuo2018** [go-logr/logr#48]
I was a little confused about the persistences of the logs.Is there a default file path for the log records??
If I did not set the file path for the log instance, will the log only print to standard out and not record to a file on the host running the program?

**Comment by thockin** [comment]
logr is just an API - you need to plug in some implementation which actually does the logging.  Take a look at https://github.com/go-logr/logr/blob/master/README.md#implementations-non-exhaustive for some implementations.
