### ISSUE TITLE
Reserved keys spec is too loose.

### ISSUE THREAD

**Issue by thockin** [go-logr/logr#5]
Spec says:

```
// While users are generally free to use key names of their choice, it's generally best to avoid
// using the following keys, as they're frequently used by implementations:
//
// - `"error"`: the underlying error value in the `Error` method.
// - `"stacktrace"`: the stack trace associated with a particular log line or error
//                   (often from the `Error` message).
// - `"caller"`: the calling information (file/line) of a particular log line.
// - `"msg"`: the log message.
// - `"level"`: the log level.
// - `"ts"`: the timestamp for a log line.
//
// Implementations are encouraged to make use of these keys to represent the above
// concepts, when neccessary (for example, in a pure-JSON output form, it would be
// necessary to represent at least message and timestamp as ordinary named values).
```

Maybe we should just reserve all keys starting with "_" or all keys starting with "logr." or even just the key named "logr" (which can be a struct) to segregate things provided by the impl from things provided by the user?

@munnerz
@DirectXMan12

**Comment by DirectXMan12** [comment]
I wouldn't be opposed to something like `logr.foo`.  I'm not sure it's enforceable in zapr, though -- we'd have to add a utility function for it to edit the zap config before constructing the underlying zap logger -- it gets configured here: https://godoc.org/go.uber.org/zap/zapcore#EncoderConfig

**Comment by thockin** [comment]
Does zap set a bunch of keys by default?

**Comment by DirectXMan12** [comment]
error, stacktrace, caller, etc are initialized by the high-level logger init function ootb, I believe.  That's where that list comes from :-)

**Comment by thockin** [comment]
What happens if a user specifies those keys?

**Comment by DirectXMan12** [comment]
I don't recall off the top of my head.  Need to double-check.

**Comment by DirectXMan12** [comment]
With Zap as the backend (basically, just passing through the logr interface to Zap -- Zapr doesn't do much preprocessing).

```go
package main

import (
	"sigs.k8s.io/controller-runtime/pkg/log/zap"
)

func main() {
	log := zap.Logger(false /* full json output */)
	
	log.Info("this uses the ts field", "ts", 8675309)
}
```

```shell
$ go run main.go
{"level":"info","ts":1565727311.7283266,"msg":"this uses the ts field","ts":8675309}
```

**Comment by thockin** [comment]
As does glogr and stdr, so ... OK.  I'll add words
