### ISSUE TITLE
extending a Logger

### ISSUE THREAD

**Issue by pohly** [go-logr/logr#63]
In https://github.com/go-logr/logr/pull/31 we discussed an approach for adding optional features to a logger and settled on optional interfaces, like this one:

https://github.com/go-logr/zapr/blob/97f3a0a6a3f0212bdc9326c2c17054e0a9cd2e9f/zapr.go#L164-L174

Users would then do something like:

```
func helper(log logr.Logger, msg string) {
	log.WithCallDepth(2).Info(msg)

	if zaplogger, ok := log.(zapr.Underlier); ok {
		log.Info("have zap logger", "zapr", zaplogger)
	}
}
```

That no longer works because logr.Logger is a struct.

**Comment by pohly** [comment]
We could add a `Logger.GetLogSink() LogSink` method and then let users cast the return value?

**Comment by pohly** [comment]
I like exporting `Sink` better. It enables the implementation of custom `With` functions because such a function then can return a copy of the logger with a modified sink:
```
// WithFooBar changes the foobar parameter in the log sink and returns a new logger with that modified sink.
// It does nothing for loggers where the sink doesn't support that parameter.
func WithFooBar(log logr.Logger, foobar int) logr.Logger {
    if foobarLogSink, ok := logger.Sink(FoobarSink); ok {
       newLog := log
       newLog.Sink = foobarLogSink.WithFooBar(foobar)
       return newLog
    }
    return log
}
```

**Comment by thockin** [comment]
Do you want to propose a PR, or I can do it later this week?

**Comment by pohly** [comment]
I can propose something tomorrow.
