### ISSUE TITLE
pkg.go.dev: subsections not rendered

### ISSUE THREAD

**Issue by pohly** [go-logr/logr#79]
https://pkg.go.dev/github.com/go-logr/logr@v1.0.0 shows subsections like this:
```
Overview

Package logr defines a general-purpose logging API and abstract interfaces to back that API. Packages in the Go ecosystem can depend on this package, while callers can implement logging with whatever backend is appropriate.

Usage ----- 
```

**Comment by pohly** [comment]
Not sure yet what acceptable markup is...

**Comment by pohly** [comment]
The bullet lists further down are rendered like pre-formated code instead of proper bullet lists.

**Comment by pohly** [comment]
https://go.dev/blog/godoc describes the supported format. Subsections and bullet lists are simply not supported.

pkg.go.dev properly renders the README.md. Perhaps we should simply move more of the content from the package documentation to that file?

The downside with that is that the README is not shown completely by default. One has to click on "Expand".

**Comment by pohly** [comment]
A less intrusive solution would be to remove the hyphens underneath the subsections.

**Comment by thockin** [comment]
I'm fine to remove the underlines

**Comment by thockin** [comment]
Or use markdown syntax:

```
# Usage
```

?  It doesn't render as a section header, but it makes the line stand out when reading.

**Comment by pohly** [comment]
I'm leaning towards `# Usage`.
