### ISSUE TITLE
handling of unexported fields

### ISSUE THREAD

**Issue by pohly** [go-logr/logr#90]
It is a conscious decision that funcr doesn't call `String`. But that begs the question how callers should log types where relevant fields are not exported. Here's an example:
```
diff --git a/funcr/funcr_test.go b/funcr/funcr_test.go
index 735cbd6..f9050a7 100644
--- a/funcr/funcr_test.go
+++ b/funcr/funcr_test.go
@@ -191,6 +191,17 @@ func (c *capture) Func(prefix, args string) {
 	c.log = prefix + " " + args
 }
 
+
+type kmeta struct {
+	namespace, name string
+}
+
+func (k kmeta) String() string {
+	return k.namespace + "/" + k.name
+}
+
+var _ fmt.Stringer = kmeta{}
+
 func TestInfo(t *testing.T) {
 	testCases := []struct {
 		name   string
@@ -200,6 +211,13 @@ func TestInfo(t *testing.T) {
 		name:   "just msg",
 		args:   makeKV(),
 		expect: ` "level"=0 "msg"="msg"`,
+	}, {
+		name: "stringer",
+		args: makeKV("meta", kmeta{namespace: "foo", name: "bar"),
+		// funcr ignores String, so there is nothing to log for the
+		// internal type (unexported field not visible through
+		// reflection).
+		expect: ` "level"=0 "msg"="msg" "meta"={}`,
 	}, {
 		name:   "primitives",
 		args:   makeKV("int", 1, "str", "ABC", "bool", true),
```

**Comment by pohly** [comment]
I agree that calling `String` is not the best choice for structured output via JSON. Logging as a struct would be better. Therefore logging `kmeta.String()` instead of the `kmeta` object (i.e. let the caller decide) is just a workaround, but not a desirable solution.

zap has [`ObjectMarshaler`](https://pkg.go.dev/go.uber.org/zap/zapcore#ObjectMarshaler) for this. It's also more efficient than reflection-based logging of complex objects.

Perhaps it makes sense to add such an API to logr after all? This was previously discussed in https://github.com/kubernetes/klog/issues/262.

Should we come back to this at some point, here's a prototype:
- [logr](https://github.com/pohly/logr/blob/ca15dec7dec08acec5226d4ea472088d16856ba6/logr.go#L481-L530)
- [zapr](https://github.com/pohly/zapr/blob/252fd4b0712151252c49b2ba37f08b7ace8ed642/zapr.go#L307-L329)

**Comment by thockin** [comment]
A few thoughts.

1) funcr doesn't handle all the input types (e.g. complex) - it probably should.

2) OK.  I guess I see the value of having a logr-defined interface that types can implement.  I don't honestly see it getting used much.

3) Not having a way to print `time.Time` in funcr is bad.  We should have a general answer to that.  :(

4) The proposal for encoder has LOTS of methods.  Do we need them all?  Can we do something simpler?  E.g. What if the `MarshalLogObject()` too no args and returned a `map[string]interface{}`, and then zapr could iterate that map and add each key-value pair to the encoder?   I didn't try to mock this up or anything yet.

5) It seems like the new `zapAny()` could handle the case of `logr.ObjectMarshaler` and pass any other value back to `zap.Any()`?

6) I don't understand the need for wrapEncoder?

**Comment by thockin** [comment]
https://github.com/thockin/zapr/commit/fcf882bebccd384202b72f6ef02f9f3a8ce1a14e as a modified counter proposal?
