### ISSUE TITLE
JSON LogSink loosely-coupled to Google Cloud Logging

### ISSUE THREAD

**Issue by DazWilkin** [go-logr/logr#97]
Thanks for logr.

I've been using logr across the components of an app, deployed to different different Google Cloud Platform (GCP) services (GKE, Cloud Functions, Cloud Run) and all use Cloud Logging.

To benefit most from Cloud Logging, I want to use [structured logging](https://cloud.google.com/logging/docs/structured-logging) but:

1. Cloud Logging requires that log entries be JSON formatted
2. Cloud Logging requires that logs use GCP-specific keys (e.g. `logging.googleapis.com/labels`, `logging.googleapis.com/sourceLocation`)

For (1), I've switched from stdr to zerologr to emit JSON-formatted logs.

This requires taking a dependency on `rs/zerolog` when all I really need is the standard library's `encoding/json`.

Unfortunately, zerologr entries omit the `caller` (file, line) struct that's almost a match for Cloud Logging's [SourceLocation](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#LogEntrySourceLocation).

Is there a way to retain this?

For (2), I'm using the GCP-specific keys when *writing* logs but I'd prefer to not be so tightly bound.

Should I consider writing a JSON LogSink?

Can I chain LogSinks or would I then also need to write a LogSink that combines to JSON and GCP-specific keys?

Thanks!

A related but different stupid question, why do LogSinks bind `Info` and `Err` to a single writer? For container logging, I'd prefer to write `Info` to `os.Stdout` but `Err` to `os.Stderr`. As it is, I can either have one or the other, or I need to have duplicate `Loggers` so that I can `stdout.Info` and `stderr.Err` (and never `stdout.Err` or `stderr.Info`) which seems redundant.

**Comment by DazWilkin** [comment]
Wrote about using logr w/ Google Cloud Logging: https://pretired.dazwilkin.com/posts/210928/

**Comment by hn8** [comment]
@DazWilkin For zerologr, you need to enable caller `With().Caller().Logger()` before passing in zerologr.New(), same for timestamp Timestamp(). Also you can customize zerolog.CallerMarshalFunc.

**Comment by DazWilkin** [comment]
@hn8 terrific. Thank you. Will try it tomorrow.

**Comment by thockin** [comment]
A few things here:

`stdr` is implemented in terms of `funcr`.  Funcr itself is very flexible and is PRETTY CLOSE to JSON.  I've considered a strict output  mode.  Filed an issue for it: https://github.com/go-logr/logr/issues/98

I suppose we'd need to add custom keys for that?  If zerologr does the job, then maybe that's a better answer instead of changing funcr?  Funcr was designed to be minimal, so it internalized all the formatting, but since other impls now build on it, I am not against making it more flexible.

OTOH it looks like you want to distinguish "logging.googleapis.com/labels" (what I think we would call `WithValues()`) and other values, right?  Most implementations flatten those into a single list, but they don't HAVE to.

E.g. I could imagine something like:

```
        log := funcr.NewJSON(
                func(obj string) { fmt.Println(obj) },
                funcr.Options{
                        LogTimestamp: true,
                        LogCaller:    funcr.All,
                        LogCallerFunc: true,
                        SavedValuesObject: "logging.googleapis.com/labels",
                        CallerObject: "logging.googleapis.com/sourceLocation",
                })
```

**Comment by DazWilkin** [comment]
Thanks both of you!

@hn8 -- works!

@thockin --

`zerologr` does the job but it involves taking a 3rd-party dependency and it's unclear to me whether I'm getting more value than `toJSON()` from it. I understand why you don't want to expand `funcr` though. 

*I know you know this (but for others)*, Cloud Logging's (agent's) ["special fields"](https://cloud.google.com/logging/docs/structured-logging#special-payload-fields) requires that my logs use these GCP-specific labels in order to convert the log entries from `textPayload` to `jsonPayload` and to surface e.g. `logging.googleapis.com/labels` as part of the JSON-formatted log in Cloud Logging (example below).

But this breaks the separation between `Logger` and `LogSink`. If I were to migrate from a conceptual Cloud Logging sink, I'd likely want to rewrite my log statements to use something other than the GCP-prefixed keys.

I *think* what I'd value is the ability to define map(s) that allow me to configure `Logger` to transform logs output and format the result as e.g. JSON.

In this case, to replace occurrences of a key  e.g. `labels` with `logging.googleapis.com/labels` so that when the logging agent receives the logs, it can format them suitably.

> **NOTE** With `zerologr`, I will need to transform `caller` (e.g. `caller":"/home/dazwilkin/.../structured-logging/cmd/main.go:73"`) into GCP's [LogEntrySourceLocation](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#LogEntrySourceLocation)

I need to review `funcr` because 'm wondering whether I could use it to achieve this kind of post-logging filters for these cases?

```YAML
insertId: iqz96zqax8g7f32x
jsonPayload:
  logger: MyName
  message: something
  k1: v1
  k2: v2
  v: 0
labels:
  compute.googleapis.com/resource_name: ""
  dog: Freddie
  foo: bar
  k8s-pod/run: ""
logName: logs/stdout
receiveTimestamp: "2021-09-28T18:39:20.733468400Z"
resource:
  labels:
    cluster_name: ""
    container_name: ""
    location: ""
    namespace_name: ""
    pod_name: ""
    project_id: ""
  type: k8s_container
severity: INFO
sourceLocation:
  file: main.go
  function: main
  line: 99
timestamp: "2021-09-28T18:39:19.393728454Z"
```

Which permits me to filter the logs:

```bash
gcloud logging read "labels.dog=\"Freddie\" "jsonPayload.logger=\"MyName\"" ...
```

**Comment by thockin** [comment]
funcr is not currently set up to allow you to intercept and mutate, but it COULD be.  But so could zerolog, I presume.  At some point, funcr and zerolog are very similar, and you have to ask why we have both.

 > I think what I'd value is the ability to define map(s) that allow me to configure Logger to transform logs output and format the result as e.g. JSON.

This is really what I am handwaving at wrt funcr (or zero).  Concretelym what if we had this:

```
// NewJSON would be a new feature, demanding strict JSON output.
log := funcr.NewJSON(
        // This is a new function signature, for JSON output.
        func(obj string) { fmt.Println(obj) },
        funcr.Options{
                LogTimestamp: true,
                LogCaller:    funcr.All,

                // LogCallerFunc would be a new feature, telling us to also log
                // the caller function name
                LogCallerFunc: true,

                // CallerObject would be a new feature, telling us to name the
                // "caller" object as specified.
                CallerObject: "logging.googleapis.com/sourceLocation",

                // SavedValuesObject would be a new feature, telling us to put
                // this KV pairs from `WithValues()` into a sub-object (not flat)
                // and give a key name for that subobject.
                SavedValuesObject: "logging.googleapis.com/labels",
        })
```

I think this collection of new features would give you want.  I am assuming
that "labels" means "WithValues()", which I need validation on.

So:

```
log.WithName("theName").WithValues("l1", "theLabel").Info("thMessage", "k1", 1, "k2", 2)
```

would produce something like (formatted for reading):

```
{
  logger:"theName",
  "logging.googleapis.com/sourceLocation": {
    "file":"main.go",
    "line":58,
    func:"main"
  },
  "level":0,
  "msg":"theMessage",
  "logging.googleapis.com/labels":{
    "l1":"theLabel"
  },
  "k1":1,
  "k2":2
}
```

**Comment by DazWilkin** [comment]
I apologize for not fully understanding your original comments; I've had a whack at  implementing `funcr` and I better understand your points|questions:

1. It would be useful to have `LogCallerFunc` and `CallerObject` but, for Cloud Logging, `CallObject` must also be transformed into the GCP-specific [LogEntrySourceLocation](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#LogEntrySourceLocation) type too (`{file,line,function}`)
2. `SavedValuesObject` (ah I now understand your interest in differentiating between `WithValues(foo...)` and e.g. `Info(msg, foo...)`) would work.

**Comment by thockin** [comment]
> CallObject must also be transformed into the GCP-specific LogEntrySourceLocation type too ({file,line,function})

That's why I added `LogCallerFunc: true` - LogCaller already has file and line in a struct.

So these sorts of changes are plausible in funcr  - would love to hear @hn8 re zerologr - we should figure out where we want the line between them to be.

**Comment by hn8** [comment]
@DazWilkin @thockin Some thoughts:
1. zerolog (and zap) tries to minimize memory alloc. You could intercept io.Writer (like how zerolog.ConsoleWriter or zerolog/journald does), but it requires json.Decode and void the benefit of zerolog IMHO.
2. zerolog's caller output can not be intercepted by Logr (only possible at io.Writer), so funcr proposal is better for your use case. Or you need to disable zerolog's caller and use runtime.Caller in custom LogSink wrapper.
3. Use `go build -trimpath` will make your life easier with runtime.Caller
4. Optional WithMapFilter interface on keyAndValues interface slice might help here (for funcr not logr since caller is LogSink feature). Users could conditionally inject mutater to rename key and reshape value. https://github.com/go-logr/zerologr/commit/e9a546d8b824834fc4daf94ed697f2366244da3f

**Comment by thockin** [comment]
I made a little time tonight:

https://github.com/go-logr/logr/compare/master...thockin:master

I don't like all of it, and I didn't get to the key-renaming part, but it gives you an idea.  You get output like:

```
{"logger":"","ts":"2021-09-30 23:44:14.833166","caller":{"file":"main.go","line":55,"function":"main.example"},"level":0,"msg":"hello","values":{"module":"example"},"val1":1,"val2":{"k":1}}
```

aka

```
{
  "logger": "",
  "ts": "2021-09-30 23:44:14.833166",
  "caller": {
    "file": "main.go",
    "line": 55,
    "function": "main.example"
  },
  "level": 0,
  "msg": "hello",
  "values": {
    "module": "example"
  },
  "val1": 1,
  "val2": {
    "k": 1
  }
}
```

**Comment by DazWilkin** [comment]
I appreciate your spending time on this, thank you!

I apologize for my naivete|stupidity, if I could provide a `Logger` with a user-defined `flatten(kvList ...interface{}) string`, could I not take the responsibility for (a) emitting a string of JSON; (b) emitting a string of JSON formatted to use GCP-specific keys?

It seems that even `string` may be too specific. In most cases logs are strings but, if my sink were e.g. a gRPC service, some database etc., it would be neat to `log` directly to these too.

**Comment by thockin** [comment]
funcr started as a trivial example, and has grown somewhat. Still, it is useful and fast.  I think that, if you really want to intercept the kvList direct, just implement a new LogSink - it's not hard or "anti-pattern" :)

Passing around the variadic list of args has a cost, so funcr tries to do it as little as  possible.

I will  think  more about the key-renaming stuff later or this weekend or something.

**Comment by thockin** [comment]
https://github.com/go-logr/logr/pull/101 is the first PR.  My master branch has a bunch queued up, I'll send PRs for those as others merge :)

The proposed result looks like:

```
        valuesAsObject := func(kvList []interface{}) []interface{} {
                return []interface{}{"logging.googleapis.com/labels", funcr.PseudoStruct(kvList)}
        }

        var log logr.Logger = funcr.NewJSON(
                func(obj string) { fmt.Println(obj) },
                funcr.Options{
                        LogCaller: funcr.All,
                        LogCallerFunc: true,
                        RenderValuesHook: valuesAsObject,
                })
        log = log.WithName("MyLogger")
        log = log.WithValues("savedKey", "savedValue")
        log.Info("the message", "key", "value")
```

Producing:

```
{"logger":"MyLogger","level":0,"caller":{"file":"example.go","line":1234,"function":"example.main"},"msg":"the message","logging.googleapis.com/labels":{"savedKey":"savedValue"},"key":"value"}
```

**Comment by thockin** [comment]
My whole commit stack can be seen at https://github.com/go-logr/logr/compare/master...thockin:master

**Comment by DazWilkin** [comment]
> post here when it's up! :)

👍 It'll be early next week as I'm away tomorrow for the weekend.

Thank you all *very* much for making this happen.

**Comment by thockin** [comment]
Nice!  Is that public now?  Ie. can I tweet it?

**Comment by thockin** [comment]
Will tweet.
